# -*- coding: utf-8 -*-
"""unsw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bczp-Cn0pVgE7I4J_AETUydlNT5KQmiX

# Network Anomaly Detection on UNSW-NB15: Random Forest vs XGBoost


**Task:** binary classification, 0 = normal traffic, 1 = attack.

## 1. Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay)

"""## 2. Load data"""

train = pd.read_csv("UNSW_NB15_training-set.csv", encoding="utf-8-sig")
test  = pd.read_csv("UNSW_NB15_testing-set.csv",  encoding="utf-8-sig")
print(train.shape, test.shape)
print(train["label"].value_counts())
train.head()

"""## 3. Preprocess (as in the paper)

### Drop id (not useful) and attack_cat (attack name, would leak the answer)
"""

y_train = train["label"]
y_test  = test["label"]
X_train = train.drop(columns=["id", "attack_cat", "label"])
X_test  = test.drop(columns=["id", "attack_cat", "label"])
print("Features:", X_train_s.shape[1])

"""### Label-encode proto, service, state"""

# Label encoding (fit on both sets so unseen categories don't cause errors)
for col in ["proto", "service", "state"]:
    le = LabelEncoder().fit(pd.concat([X_train[col], X_test[col]]))
    X_train[col] = le.transform(X_train[col])
    X_test[col]  = le.transform(X_test[col])

"""### Min-Max scale all features to [0, 1]"""

# Scaling (fit on train only)
scaler = MinMaxScaler()
X_train_s = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_s  = pd.DataFrame(scaler.transform(X_test),      columns=X_test.columns)

"""## 4. Train the two models
Settings follow the paper: Random Forest with 100 trees, XGBoost with default settings and `logloss`.
"""

rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
xgb = XGBClassifier(eval_metric="logloss", random_state=42, n_jobs=-1)

rf.fit(X_train_s, y_train)
xgb.fit(X_train_s, y_train)
print("Training done")

"""## 5. Evaluate on the test set"""

def evaluate(model, name):
    pred = model.predict(X_test_s)
    prob = model.predict_proba(X_test_s)[:, 1]
    return {"Model": name,
            "Accuracy":  accuracy_score(y_test, pred),
            "Precision": precision_score(y_test, pred),
            "Recall":    recall_score(y_test, pred),
            "F1-Score":  f1_score(y_test, pred),
            "AUC":       roc_auc_score(y_test, prob)}

results = pd.DataFrame([evaluate(rf, "Random Forest"), evaluate(xgb, "XGBoost")]).set_index("Model")
results.round(4)

"""## 6. Charts"""

results.T.plot(kind="bar", figsize=(8, 4))
plt.title("Random Forest vs XGBoost")
plt.ylabel("Score")
plt.ylim(0.5, 1.0)
plt.xticks(rotation=0)
plt.grid(axis="y", alpha=0.3)
plt.show()